# Generated by Django 5.1.6 on 2025-02-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactme',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('dismissed', 'Dismissed'), ('interested', 'Interested')], default='New', max_length=50),
        ),
    ]
